"""create traveler_profiles table

Revision ID: 47035b9239e4
Revises: 95eb9436f15e
Create Date: 2026-08-25 19:04:37.653534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '47035b9239e4'
down_revision: Union[str, Sequence[str], None] = '95eb9436f15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# FIXED — found by actually running the upgrade/downgrade/upgrade
# roundtrip (MASTER_RULES.md's "empirical verification" requirement),
# not assumed from the AUTH-08 migration's comment alone: unlike
# op.add_column (95eb9436f15e_add_role_column_to_users.py's own bug),
# op.create_table DOES correctly auto-create these 4 Postgres enum
# TYPEs as part of table DDL — but op.drop_table does NOT drop them
# back. A downgrade followed by a re-upgrade failed with
# `asyncpg.exceptions.DuplicateObjectError: type "travel_preference"
# already exists`. Explicit drop() calls below, checkfirst=True so
# this migration stays safely re-runnable — same fix shape as
# 95eb9436f15e, applied to the opposite (create vs. drop) side of the
# same underlying gap in Alembic's autogenerate.
travel_preference_enum = postgresql.ENUM(
    'solo', 'family', 'couple', 'business', 'adventure', 'luxury', 'budget',
    name='travel_preference',
)
budget_level_enum = postgresql.ENUM('economy', 'mid_range', 'premium', 'luxury', name='budget_level')
accommodation_preference_enum = postgresql.ENUM(
    'hotel', 'apartment', 'hostel', 'resort', name='accommodation_preference'
)
transportation_preference_enum = postgresql.ENUM(
    'flight', 'train', 'car', 'walking', name='transportation_preference'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('travel_preference', sa.Enum('solo', 'family', 'couple', 'business', 'adventure', 'luxury', 'budget', name='travel_preference'), nullable=True),
    sa.Column('budget_level', sa.Enum('economy', 'mid_range', 'premium', 'luxury', name='budget_level'), nullable=True),
    sa.Column('accommodation_preference', sa.Enum('hotel', 'apartment', 'hostel', 'resort', name='accommodation_preference'), nullable=True),
    sa.Column('transportation_preference', sa.Enum('flight', 'train', 'car', 'walking', name='transportation_preference'), nullable=True),
    sa.Column('food_preferences', sa.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('preferred_ui_language', sa.String(length=8), nullable=True),
    sa.Column('preferred_travel_language', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traveler_profiles_user_id'), 'traveler_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traveler_profiles_user_id'), table_name='traveler_profiles')
    op.drop_table('traveler_profiles')
    # ### end Alembic commands ###
    # FIXED — see module-level comment above.
    travel_preference_enum.drop(op.get_bind(), checkfirst=True)
    budget_level_enum.drop(op.get_bind(), checkfirst=True)
    accommodation_preference_enum.drop(op.get_bind(), checkfirst=True)
    transportation_preference_enum.drop(op.get_bind(), checkfirst=True)
